/**
 * @namespace flexygo.culture.eses
 */
var flexygo;
(function (flexygo) {
    var culture;
    (function (culture) {
        var ptpt;
        (function (ptpt) {
            ptpt.process = {
                executing: 'Executando processo...',
            };
            ptpt.dependecymanager = {
                sort: 'Classificar',
                valuedep: 'Valor',
                classdep: 'Classe',
                combodep: 'Suspensa',
                enabledep: 'Ativado',
                visibledep: 'Visível',
                requireddep: 'Obrigatório',
                CustomProperty: 'Custom Property Dep.',
                save: 'Salve',
                addmore: 'Adicionar mais propriedades dependentes',
                sqlvalue: 'SQL Valor',
                sqlclass: 'SQL Classe',
                sqlcombofilter: 'Filtro SQL para lista suspensa',
                sqlcombosentence: 'SQL para lista suspensa',
                enabledvalues: 'Valores que permitem',
                disabledvalues: 'Valores que não permitem',
                sqlenabledsentence: 'SQL que permite',
                visiblevalues: 'Valores que tornam visíveis',
                hiddenvalues: 'Valores que escondem',
                visiblesentence: 'Instrução SQL visível',
                requiredvalues: 'Valores para obrigatórios',
                notrequiredvalues: 'Valores para não obrigatórios',
                requiredsentence: 'SQL para obrigatórios',
                description: 'Descrição',
                valueApply: 'Valores afetados',
                CusPropertyName: 'Nome Custom Control',
                SQLCustomProperty: 'SQL Custom Property',
                connectionstrings: 'Cadeias de conexão',
                connStringvalues: 'Valores da cadeia de conexão',
                relateddep: 'Dependências relacionadas'
            };
            ptpt.develop = {
                developer: 'Desenvolvedor',
                adminarea: 'Área de design',
                help: 'Ajuda',
                dependencymanager: 'Gerenciamento de dependências',
                filtermanager: 'Gerenciamento de filtros',
                modulemanager: 'Gerenciamento de módulos',
                nodemanager: 'Gerenciamento de nodes',
                settings: 'Configuração',
                wizard: 'Assistente',
                editproperties: 'Editar Propriedades',
                modules: 'Modulos',
                collection: 'Coleção',
                page: 'Página',
                object: 'Objeto',
                imagemanager: 'Configuração de imagems',
                documentmanager: 'Configuração de documentos',
                mailmanager: 'Configuração de Correio',
                viewobject: 'Ver objeto',
                security: 'Segurança',
                objectsecurity: 'Segurança de Objeto',
                objectprocesssecurity: 'Processos del Objeto',
                selectobject: 'Por favor selecione uma página que contenha um objeto',
                objectpropertysecurity: 'Segurança de Propriedades',
                pageSettings: 'Propriedades da página',
                chatter: 'Chatter',
                users: 'Usuarios',
                roles: 'Roles',
            };
            ptpt.history = {
                historyempty: 'Histórico de navegação vazio',
                showmore: 'Ver mais',
            };
            ptpt.navigation = {
                relatedobjects: 'Objetos relacionados',
                reports: 'Relatórios',
                noelements: 'Não há elementos',
                popupwarning: 'As configurações do seu navegador estão bloqueando as janelas pop-up.',
                reportmaxrows: 'Este relatório usa {0} linhas para filtrar e excede o limite de {1}. Aplique primeiro um filtro mais restritivo.'
            };
            ptpt.msg = {
                confirm: 'Confirme a ação',
                fieldrequired: 'O campo é obrigatório',
                copied: 'Copiado',
            };
            ptpt.flxkanban = {
                addCard: 'Adicionar novo',
            };
            ptpt.flxedit = {
                addfields: 'Adicionar campos',
                selectall: 'Selecionar tudo',
                selectnone: 'Desmarcar tudo',
                createwarning: 'Selecione pelo menos um campo.',
                appendwarning: 'Selecione um tipo e nome de campo.',
                createfields: 'Adicionar campos',
                enterfieldname: 'Nome do campo',
                selecttype: 'Selecione o tipo de dados',
                seedependencies: 'Veja as dependências',
                templates: 'Modelos',
                objectsettings: 'Configuração de objeto',
                label: 'Rótulo',
                style: 'Estilo',
                classname: 'Nome da clase',
                selecticon: 'Selecione um icono',
                selectcontroltype: 'Selecione um tipo de controle',
                locked: 'Trancado',
                required: 'Obrigatório',
                hidden: 'Escondido',
                addseparatora: 'Adicionar Separador Acima',
                addseparatorb: 'Adicionar Separador baixo',
                addplaceholder: 'Adicionar um controle de posição',
                save: 'Salve',
                close: 'Fechar',
                areyousuretitle: 'Tem alterações não salvas',
                areyousuremsg: 'Você realmente deseja fechar esta página?',
                areyousuremsgyes: 'Sim',
                areyousuremsgno: 'Não',
                emptyproperty: 'Propriedade vazia',
                addproperties: 'Adicionar Propriedades',
                propertyname: 'Nome da propriedad',
                propertylabel: 'Rótulo da propriedad',
                adddetachedproperty: 'Adicionar propiedad desconectada',
                selecttable: 'Selecione Tabela',
                loadmore: 'Role para carregar mais',
                hasdependencies: 'Lança dependências',
                hasdependingproperties: 'Afetado por dependências'
            };
            ptpt.flxeditgrid = {
                addrow: 'Adicionar linha',
                removeselection: 'Remover seleção',
                hide: 'Ocultar',
                settings: 'Configuração',
                deleteconfirm: 'Você quer deletar os itens selecionados?',
                startinfo: 'Primeiro você precisa definir a grade de edição',
            };
            ptpt.flxfilter = {
                searchplaceholder: 'Procurar por: ',
                showall: 'Mostre tudo',
            };
            ptpt.flxarea = {
                noprocesses: 'Sem processos associados',
                doubleclickexpand: 'Clique para expandir / recolher Processos...',
            };
            ptpt.flxgipe = {
                butonadd: 'Adicionar',
                buttonload: 'Cargar',
                buttonsave: 'Salve',
                buttoncancel: 'Cancelar',
                dialogloadtitle: 'Fluxo de carga',
                dialogsavetitle: 'Salve Fluxo',
                dialogpropertiestitle: 'Propriedades',
                dialogtemplatetitle: 'Selecione o modelo',
                dialogdebugtitle: 'Execução de depuração',
                errornoworkflowselected: 'Selecione um fluxo para fazer o upload',
                errornoversionselected: 'Selecione uma versão de fluxo',
                confirmunsavedchanges: 'Tem alterações não salvas. Você deseja continuar?',
                labelarea: 'Area:',
                labelmodule: 'Módulo:',
                labelname: 'Nome:',
                labeldescrip: 'Descrição:',
                labelversion: 'Versão:',
                labeltop: 'Posição X:',
                labelleft: 'Posição Y:',
                labelheight: 'Alto:',
                labelwidth: 'Largura:',
                labellabel: 'Rótulo:',
                labelobject: 'Objeto:',
                labelprocess: 'Processo:',
                labelworkflow: 'Fluxo:',
                labeldecission: 'Decisión:',
                labelevent: 'Evento:',
                labelactive: 'Ativo:',
                labelstatus: 'Estado:',
                labelresult: 'Resultado:',
                labelerrormessage: 'Mensagem de erro:',
                labelrelations: 'Relações de parâmetro:',
                labeloutputparams: 'Parâmetro de saída:',
                labelbackgroundcolor: 'Cor de fundo:',
                labelbordercolor: 'Cor da borda:',
                labeltextcolor: 'Cor do texto:',
                treeinnode: 'Parâmetros de entrada:',
                treeoutnode: 'Parâmetros de salida:',
                workflowareaplaceholder: 'Selecione area...',
                workfloworiginplaceholder: 'Selecione origem...',
                workflowmoduleplaceholder: 'Selecione módulo...',
                workflownameplaceholder: 'Coloque Nome...',
                workflowversionplaceholder: 'Selecione Versão...',
                searchtemplates: 'Pesquisar em modelos...',
                editortemplates: {
                    process: 'Processo',
                    object: 'Objeto',
                    decission: 'Decisão',
                    event: 'Evento',
                    workflow: 'Fluxo',
                    label: 'Rótulo',
                    toggleall: 'Marque / desmarque tudo',
                },
                editortoolbar: {
                    new: 'Novo',
                    open: 'Abrir',
                    save: 'Salve',
                    generate: 'Gerar',
                    up: 'Fluxo externo',
                    down: 'Fluxo interno',
                    run: 'Execute o Fluxo',
                    debug: 'Depurar Fluxo',
                    select: 'Selecionar',
                    pan: 'Mover',
                    undo: 'Desfazer',
                    redo: 'Refazer',
                    cut: 'Cortar',
                    copy: 'Copie',
                    paste: 'Colar',
                    delete: 'Retirar',
                    group: 'Grupo',
                    ungroup: 'Desagrupar',
                    workflow: 'Fluxo',
                    object: 'Objeto',
                    process: 'Processo',
                    decission: 'Decisão',
                    event: 'Evento',
                    connect: 'Conexão',
                    fit: 'Ajustar',
                    zoomin: 'Mais Zoom',
                    zoomout: 'Menos Zoom',
                    actualsize: 'Tamanho real',
                    templates: 'Modelos',
                    label: 'Rótulo',
                    properties: 'Propriedades',
                },
                messages: {
                    savefirst: 'Salvar ou gráfico para poder Gerar el Fluxo',
                    workflowgenerated: 'Fluxo gerado com sucesso',
                    workflowsaved: 'Fluxo salvado com éxito',
                },
                popupmenu: {
                    workflowproperties: 'Propriedades del Fluxo',
                    view: 'Ver',
                    properties: 'Propriedades',
                    enter: 'Entrar',
                    new: 'Novo',
                    listparams: 'Ver Parâmetros',
                },
            };
            ptpt.filtermanager = {
                choosefilter: 'Escolha o filtro',
                objectname: 'Objeto',
                filtertype: 'Tipo de filtro',
                properties: 'Propriedades',
                fields: 'Campos',
                unsaved: 'Existem alterações não salvas. Você quer continuar?',
                sure: 'Está seguro?',
                add: 'Adicionar',
                errornofilter: 'Por favor, adicione um novo filtro primeiro.',
                errornofields: 'Por favor, adicione pelo menos um campo de filtro.',
                save: 'Salve',
                delete: 'Retirar',
            };
            ptpt.sortmanager = {
                sort: 'Ordenar',
                fields: 'Campos',
                apply: 'Aceitar',
                clean: 'Limpiar',
                groups: 'Agrupamentos',
                applied: 'Aplicado'
            };
            ptpt.flxlist = {
                noentriesfound: 'Sem resultados.',
                warning: 'O módulo não possui um modelo, mas possui uma seção html específica. Mostrando a configuração do módulo.',
                currentfiltervalues: 'Salvar valores de filtro atual.',
                removecurrentfiltervalues: 'Certamente você deseja excluir esta filtragem que você salvou?.',
                name: 'Nome',
                generic: 'Genérico',
                savefilter: 'Salvar filtro',
                selectfilterfirst: 'Selecione um filtro primeiro',
                save: 'Salve',
            };
            ptpt.flxmail = {
                nomails: 'Nenhum email encontrado',
                nosettings: 'Sua conta de e-mail não foi configurada. Clique para configurá-la.',
                loadmore: 'Carregue mais ',
                folders: 'Pastas',
                address: 'Endereço',
                subject: 'Caso',
                body: 'Corpo',
                mindate: 'Data mínima',
                maxdate: 'Data máxima',
                unseen: 'Apenas não lida',
                sync: 'Sincronizando',
                waitsync: 'Espere que a sincronização termine.',
                nomail: 'Email não encontrado.',
                nomailalert: 'O correio não foi encontrado no servidor.',
            };
            ptpt.flxmodule = {
                delete: 'Retirar',
                save: 'Salve',
                new: 'Novo',
                edit: 'Editar',
                view: 'Ver',
                print: 'Imprimir',
                printpage: 'Imprimir página',
                printmodule: 'Imprimir módulo',
                help: 'Ajuda',
                settings: 'Configuração',
                process: 'Processo',
                report: 'Relatório',
                export: 'Exportar',
                back: 'Retornar',
                unknown: 'Função desconhecida',
                templates: 'Plantillas',
                noprop: 'Modulo sem Propriedades.',
                requiredsaving: 'Preencha todos os parâmetros necessários antes de salvar como:',
                noparams: 'Não há parâmetros para recuperar.',
                requiredrunning: 'Preencha todos os parâmetros obrigatórios antes de ejecutar.',
                requiredreport: 'Preencha todos os parâmetros obrigatórios antes de abrir el Relatório.',
                deleted: 'Excluido :)',
                saved: 'Salvo :)',
                uniqueBagError: 'Campo chave única indefinida.',
                nofieldBagError: 'O campo não foi encontrado <b>{0}</b>. Adicione-o à consulta ou remova o botão de opção.',
                noItemsSelected: 'Selecione um item da lista primeiro.',
            };
            ptpt.flxnav = {
                notimplemented: 'Ação não implementada',
                pIdNotespecified: 'Id de processo não especificado',
                urlnotespecified: 'Url não especificada',
                autoSQlnovalidtype: 'Nó SQL gerado automaticamente inválido',
                webcomponentnotspecified: 'Componente web não especificado.',
                helpidnotspecified: 'Id Ajuda no especificada',
                moreinfo: 'Mais informação.',
            };
            ptpt.image = {
                browsebutton: 'Pesquise',
                browsebuttontooltip: 'Você pode pesquisar ou arrastar uma imagem',
                savebutton: 'Salve',
                removebutton: 'Retirar',
                cropbutton: 'Aparar',
                movebutton: 'Mover',
                zoombutton: 'Zoom',
                rotatebutton: 'Girar',
                scalebutton: 'Escalar',
                aspectratiobutton: 'Relação de aparência',
                resetbutton: 'Reiniciar',
                downloadbutton: 'Download',
                free: 'Sem custos',
                errorfiletype: 'Só aceita imagens',
                errorfilenumber: 'Só aceia uma imagem',
                infotostart: 'Pesquise ou arraste uma imagem para começar',
                errorfilename: 'A imagem não tem nome',
                errorrootpath: 'Rota raiz',
                extension: 'Extensão de arquivo não aceita.',
            };
            ptpt.documentmanager = {
                upload: 'Envio',
                info: 'Pesquise ou arraste documentos',
                saved: 'Salvou',
                save: 'Salve',
                return: 'Retorna',
                removed: 'Removido',
                errorsaving: 'Erro ao salvar',
                errorremoving: 'Erro ao excluir',
                copy: 'copiar para área de transferência',
                preview: 'Pré-visualização',
                edit: 'Editar',
                remove: 'Retirar',
                disk: 'Disco',
                diskfiles: 'Arquivos de disco',
                diskfolders: 'Pasta',
                drive: 'Drive',
                dropbox: 'Dropbox',
                download: 'Download',
                link: 'Ligação',
                filter: 'Filtros',
                folderorfile: 'Pasta ou arquivo',
                browsernotsupported: 'Navegador não suportado',
                settings: 'Definições',
                permissionerror: 'Desculpe, você não tem permissões',
                documentempty: 'Documento vazio',
                view: 'Visualizar',
                downloadall: 'Baixe todos os documentos',
                nodocuments: 'Nenhum documento para download',
                msgremove: 'Tem certeza de que deseja excluir o documento?',
                sendselection: 'Enviar documentos selecionados pelo correio',
                noselection: 'No hay documentos seleccionados',
            };
            ptpt.imagemanager = {
                upload: 'Upload',
                settings: 'Definições',
                msgremove: 'Tem certeza que deseja deletar a imagem?',
                msgremoveall: 'Tem certeza que deseja remover TODAS as imagens?',
                removed: 'Imagem removida',
                removedall: 'Todas as imagens foram removidas',
                errorremoving: 'Erro ao excluir imagem',
                uploaded: 'imagem carregada',
                erroruploading: 'Erro ao carregar a imagem',
                updated: 'Imagem atualizada',
                errorupdating: 'Erro ao atualizar imagem',
                permissionerror: 'Desculpe, você não tem permissões',
                imageepmty: 'Imagem vazia',
                downloadall: 'Baixe todas as imagens',
                deleteall: 'Apagar todas as imagens',
                errordownload: 'Erro ao baixar imagens',
                noimages: 'Não tem imagem',
            };
            ptpt.upload = {
                uploaded: 'Carregado',
                error: 'Error de subida',
                info: 'Arraste para fazer upload',
                extension: 'Extensão de arquivo não aceita.',
            };
            ptpt.file = {
                saved: 'Arquivo salvo ;)',
                errorsaving: 'Erro ao salvar o arquivo :(',
                resultbase64: 'Arquivo carregado com sucesso',
                extension: 'Extensão de arquivo não aceita.',
            };
            ptpt._export = {
                success: 'Dados exportados com sucesso ;)',
                error: 'Erro ao exportar dados :(',
                exportinglist: 'Exportando lista',
                exportlimit: 'O número máximo de registros para exportar foi excedido, use um filtro mais restritivo',
            };
            ptpt.menumanager = {
                deleteMenu: 'Limpar menu',
                deleteMenuquestion: 'Tem certeza de que deseja conferir este menu e todos os seus filhos?',
                empty: 'Crie um novo menu para navegar!',
                menus: 'Menus',
                new: 'Novo',
                refresh: 'Atualizar',
                moreoptions: 'Mais opções',
                delete: 'Excluir',
                edit: 'Editar',
                submenus: 'Submenus',
                newsubmenu: 'Submenu Novo',
            };
            ptpt.modulemanager = {
                save: 'Salve',
                searchmodules: 'Pesquisar módulos',
                cancel: 'Cancelar',
                tabid: 'Identificador de aba',
                tabtitle: 'Título da aba',
                tabdescrip: 'Descrição',
                selecttabicon: 'Selecione um ícone',
                classification: 'Classificação',
                addnewtabmodule: 'Adicionar um módulo de aba',
                changepagerelation: 'Mudar a relação do módulo com a página',
                configmodule: 'Configurar módulo',
                removemodule: 'Remover módulo',
                events: 'Eventos vinculados',
                security: 'Segurança do módulo',
                tabMode: 'Tipo de aba',
            };
            ptpt.moduletab = {
                emptytabs: 'Abas vazias',
                nocontent: 'Sem resultados.',
            };
            ptpt.nodemanager = {
                save: 'Salve',
                title: 'Gerenciador de nó',
                deletenode: 'Excluir nodo',
                deletenodequestion: 'Tem certeza de que deseja excluir este nó??',
                addfields: 'Adicionar campos',
            };
            ptpt.objectmanager = {
                selecticon: 'Selecione un ícone',
                validicon: 'Selecione ícone válido',
                objectname: 'Nome do objeto',
                validobjectname: 'Insira o nome de um objeto',
                objectdescription: 'Descrição do objeto',
                validobjectdescription: 'Insira uma descrição do objeto',
                collectionname: 'Nome da Coleção',
                validcollectionname: 'Introduzca el Nome da Coleção',
                collectiondescription: 'Descrição da Coleção',
                validcollectiondescription: 'Introduzca la descrição da Coleção',
                datasource: 'Origem de datos',
                fromtable: 'De uma Tabela',
                fromview: 'De uma vista',
                fromnewtable: 'De uma nova tabela',
                selectcnnstring: 'Selecione a string de conexão',
                validcnnstring: 'Você deve selecionar uma string de conexão',
                selecttable: 'Selecione um origem',
                validorigin: 'Indique uma origem válida',
                newtablename: 'Nome de nova tabela',
                validnewtablename: 'Digite o Nome da nova tabela',
                viewkeyfields: 'Chave primária',
                validviewkeyfields: 'Introduzca chave primária',
                savecontinue: 'Salve e continue',
                continue: 'Prosseguir',
                listtemplate: 'Modelo de lista',
                edittemplate: 'Modelo de edição',
                viewtemplate: 'Modelo de exibição',
                objectcreated: 'Objeto criado',
                selectoption: 'Selecione uma opção',
                listform: 'Mostrar o formulário de <b> Lista </b>.',
                editform: 'Mostrar o formulário de <b>edição</b>.',
                objectconfig: 'Mostrar configuração de <b>Objeto</b>.',
                collectionconfig: 'Mostrar Configuração da <b>Coleção</b>.',
                showrelations: 'Mostrar <b>relações</b>.',
                saved: 'Salvou',
                basicinfo: 'Informação básica',
                objectproperties: 'Propriedades',
                listsettings: 'Listas',
                displaysettings: 'Modelos',
                end: 'Fín',
                colproperties: 'Propriedades Edit grid (opcional)',
                save: 'Salve',
                filtersettings: 'Configuração do filtros',
            };
            ptpt.flxpropertymanager = {
                addfields: 'Clique em "Adicionar campos" para começar.',
                label: 'Rótulo',
                style: 'Estilo',
                classname: 'Nome da clase',
                selecticon: 'Selecione o ícone',
                selectcontroltype: 'Selecione o tipo de controle',
                locked: 'Trancado',
                required: 'Obrigatório',
                hidden: 'Escondido',
                addseparatora: 'Adicionar Separador acima',
                addseparatorb: 'Adicionar Separador bajo',
                addplaceholder: 'Adicionar um controle de posição',
                save: 'Salve',
                close: 'Fechar',
                hasdefinition: 'Verifique a tabela da propriedade:',
            };
            ptpt.flxversioninfo = {
                currentversion: 'Versão actual ({{CurrentVersion}}).',
                lastversion: 'Última Versão ({{LastVersion}}).',
                updatedversion: 'O aplicativo é atualizado.',
                pendingchanges: 'Existem modificações pendentes para revisão',
                reviewchanges: 'Mostrar modificaciones pendentes',
                newupdate: 'Há uma nova versão disponível ({{LastVersion}}).',
                update: 'Atualizar',
                info: 'Informações',
                test: 'Executar teste',
                delete: 'Excluir',
                deleting: 'Excluindo versão',
                updating: 'Atualizando',
                initupdate: 'Inicializando atualización...',
                estatusupdatingservice: 'Atualizando Serviço...',
                estatuscheckingpackages: 'Comprobando pacotes...',
                estatusdownloadingversion: 'Baixando nueva Versão...',
                estatusfinished: 'Finalizado',
                estatusupdatedatabase: 'Atualizando base de dados',
                estatusupdateiis: 'Actualizando aplicativo web',
                applicationwillreset: 'O aplicativo está sendo reiniciado...',
                updatesuccessful: 'Atualização bem sucedida!',
                oldversion: 'Versão anterior ({{VersionNumber}})',
                newversion: 'Versão posterior S({{VersionNumber}})',
                confirmupdate: 'Tem certeza que deseja atualizar o aplicativo?',
                confirmdelete: 'Tem certeza que deseja remover o versão?',
                infotitle: 'informação da Versão',
                deletesuccessful: 'Versão deletada com sucesso!',
                infoversion: 'Número de Versão:',
                infopath: 'Caminho virtual:',
                infodatabase: 'Base de dados:',
                confirmwarningtitle: 'Atenção!',
                confirmwarninglabel: 'Por favor, confirme essas operações:',
                switch: 'Mudar para esta versão',
                confirmswitch: 'Tem certeza de que deseja mudar para esta versão?',
                releasenotes: 'Notas da versão',
                oldversionvalue: 'Valor versão anterior',
                customvalue: 'Valor personalizado',
                newversionvalue: 'Valor da nova versão',
                manualvalue: 'Valor manual',
                applychanges: 'Aplicar mudanças',
                nochanges: 'Não há mudanças marcadas para serem aplicadas',
                changecount: 'Tem certeza de que deseja aplicar as {{count}} alterações?',
                applychangessuccesful: 'Mudanças aplicadas com sucesso',
            };
            ptpt.viewmanager = {
                properties: 'Propriedades',
                fields: 'Campos',
                unsaved: 'Existem alterações não salvas. Você quer continuar?',
                add: 'Adicionar',
                errornofilter: 'Por favor, Adicione uma nova visão primeiro.',
                errornofields: 'Por favor, adicione ao menos um campo.',
                errornosql: 'O campo SQL não pode ficar em branco.',
                validate: 'Validar',
                errorduplicateprop: 'Campo {0} já existe nesta lista.',
                save: 'Salve',
                cancel: 'Cancelar',
                viewwizard: 'Assistente de Vistas',
                selectobject: 'Por favor, selecione um objeto',
                openwizard: 'Abrir assistente',
                saved: 'Salvou :)',
            };
            ptpt.templates = {
                addnewtemplate: 'Adicionar modelo',
            };
            ptpt.flxscheduler = {
                objects: 'Objetos',
                chooseobjects: 'Selecione um Objeto',
            };
            ptpt.flxscheduleryear = {
                january: 'Janeiro',
                february: 'Fevereiro',
                march: 'Março',
                april: 'Abril',
                may: 'Maio',
                june: 'Junho',
                july: 'Julho',
                august: 'Agosto',
                september: 'Setembro',
                october: 'Outubro',
                november: 'Novembro',
                december: 'Dezembre',
                mn: 'Se',
                tu: 'Te',
                we: 'Qa',
                th: 'Qi',
                fr: 'Sx',
                sa: 'Sa',
                su: 'Do',
            };
            ptpt.flxsearch = {
                search: 'Pesquisar...',
                pleasewrite: 'Por favor, escreva o texto para pesquisar',
                speak: 'Fale agora...',
                pleaseobject: 'Por favor, selecione um objeto primeiro',
                searchnode: 'Procurar',
            };
            ptpt.text = {
                map: 'Clique no mapa',
                errormap: 'Endereço não encontrado',
                api: 'Chave API do Google não encontrada.',
                apihelp: 'Consulte nossa ajuda para descobrir como obter.',
                nophone: 'Insira um número de telefone',
                nomail: 'Digite um endereço de e-mail',
            };
            ptpt.flxfunnel = {
                data: 'Não há dados',
            };
            ptpt.flxtimeline = {
                withoutDescription: 'Sem Descrição',
                withoutRegisters: 'Sem Registros',
                hour: 'Hora',
                today: 'Hoje',
                day: 'Día',
                week: 'Semana',
                month: 'Mês',
                year: 'Ano',
                navigation: 'Navegação',
                range: 'Intervalo',
                title: 'Ajuda e atalhos ',
                description: 'Descrição',
                action: 'Açao',
                selectitem: 'Selecionar elemento',
                multiselectitems: 'Seleção múltipla de elementos',
                multiselectbyrange: 'Seleção múltipla de itens por intervalo de tempo',
                multiselectbyrangegroup: 'Seleção múltipla de itens por intervalo de tempo em um grupo',
                createitem: 'Criar elemento',
                createitemwithrange: 'Criar item com intervalo',
                edititem: 'Editar elemento',
                openeditview: 'Abrir visualização de edição',
                zoom: 'Mudar intervalo de tiempo',
                navigationtime: 'Navegação no tempo',
                or: 'ou',
                to: 'Para',
                withoutpercentage: 'Sem porcentagem',
                notsupported: 'Tamanho de tela não suportado',
            };
            ptpt.flxfilebrowser = {
                saved: 'Salvou',
                errorsaving: 'Erro ao salvar',
                errorremoving: 'Erro ao deletar',
                permissionerror: 'Desculpe, você não tem permissões',
                documentempty: 'Documento vazio',
                itemsselected: 'Itens selecionados',
                emptyfolder: 'A pasta está vazia',
                existingfiles: 'Os arquivos já existem no servidor',
                overwritefiles: 'Tem certeza que deseja excluí-los?',
                deleting: 'Excluindo',
                items: 'Itens',
                sure: 'Tem certeza?',
                currentfolder: 'Pasta atual',
                uploadfiles: 'Fazer upload de arquivos',
                addfolder: 'Criar pasta',
                download: 'Download',
                delete: 'Excluir',
                goback: 'Volte',
                processingdownload: 'Processando download'
            };
            ptpt.chatter = {
                composerplaceholder: 'Escreva algo',
                sendbutton: 'Registro',
                startinfo: 'Você deve primeiro configurar o chatter',
                deleteconfirm: 'Tem certeza que quer deletar a mensagem?',
                saveButton: 'Salve',
            };
            ptpt.offline = {
                createobjecttitle: 'Adicionar um novo objeto ao aplicativo',
                createobjectcontent: 'Você pode criar um novo objeto ou construir sobre um existente',
                createobjectbuttonnew: 'Novo objeto',
                createobjectbuttonbased: 'Baseado no objeto',
                enablewebapiconfirmation: 'Para utilizar o aplicativo offline, é necessário ativar a API Web e reiniciar o aplicativo. Você deseja reiniciar o aplicativo agora?',
            };
            ptpt.offlineemulator = {
                ios: 'Mudar para o modo iOS',
                md: 'Mudar para o modo Android',
            };
            ptpt.combobuilder = {
                datasource: 'Fonte de dados',
                fromtable: 'Tabela',
                fromview: 'Vista',
                selectcnnstring: 'Selecione a string de conexão',
                validcnnstring: 'Você deve selecionar a string de conexão',
                selecttable: 'Selecione uma origem',
                validorigin: 'Indique uma origem válida',
                viewkeyfields: 'Campos-chave da vista',
                saved: 'Salvou',
                save: 'Salve',
                cancel: 'Cancelar',
                selectvaluefield: 'Selecione o campo de valor',
                selectdisplayfield: 'Selecione o campo de exibição',
                selectadditionalfield: 'Selecione campos adicionais',
                selectorderfield: 'Selecione o campo para ordenar os resultados',
                comboassistant: 'Assistente',
                cnnstring: 'String de conexão',
                origin: 'Origem',
                sqlsentence: 'Sentencia SQL',
                valuefield: 'Campo a Salve',
                displayfield: 'Campo de exibição',
                additionalfield: 'Campos adicionais',
                orderfield: 'Campo para ordenar',
                validvaluefield: 'Indique um campo para salvar',
                validdisplayfield: 'Indique um campo para exibir',
                validorderfield: 'Indique um campo para ordenar',
                validsqlsentence: 'A instrução SQL não é válida',
            };
            ptpt.formatsmanager = {
                formatassistant: 'Assistente',
                field: 'Campo',
                selectfield: 'Indique el campo',
                validfield: 'Por favor, insira um campo válido',
                validformat: 'Forneça um tipo de formato válido',
                selectformat: 'Indique un tipo de formato',
                formattype: 'Tipo de formato',
                saved: 'Salvou',
                nosaved: 'Nenhum formato foi salvo',
                decimal: 'Formato de decimal',
                isdate: 'Formato de data',
                translate: 'Traduzir texto',
                save: 'Salve',
                cancel: 'Cancelar',
                casetrue: 'Se for verdade',
                casefalse: 'Se for falso',
                boolformat: 'Formato booleano',
                isnull: 'O valor é nulo',
                numdecimals: 'Número de decimais',
                switchformat: 'Switch',
                casenotnull: 'O valor não é nulo',
                stringformat: 'Texto para formatear',
                stringtype: 'Tipo de formato de texto',
                validstringformat: 'Selecione um tipo de formato de texto válido',
                uppercase: 'Letras maiúsculas',
                lowercase: 'Minúsculas',
                characternumber: 'Número de caracteres a serem exibidos',
                addoption: 'Adicionar uma opção',
                addelse: 'Adicionar uma opção por defecto',
                dateformat: 'Tipo de formato de data',
                selectdateformat: 'Selecione um tipo de formato de data',
                validdateformat: 'Selecione um tipo de formato de data válido',
                dateLT: '19:05',
                dateLTS: '19:05:57',
                dateL: '13/07/2021',
                datel: '13/7/2021',
                dateLL: '13 de julho de 2021',
                datell: '13 jul. 2021',
                dateLLL: '13 de julio de 2021 19:05',
                datelll: '13 jul. 2021 19:05',
                dateLLLL: 'Terça-feira 13 de julho de 2021 19:05',
                datellll: 'Terç., 13 jul. 2021 19:05',
                translatesentence: 'Texto para traduzir',
                option: 'opção',
                result: 'Resultado',
                elseoption: 'Por padrão',
            };
            ptpt.imports = {
                template: 'Arquivo de modelo',
            };
            ptpt.htmlreport = {
                generate: 'Gerando relatório',
            };
        })(ptpt = culture.ptpt || (culture.ptpt = {}));
    })(culture = flexygo.culture || (flexygo.culture = {}));
})(flexygo || (flexygo = {}));
//# sourceMappingURL=language-ptpt.js.map